---
- name: Transfer and execute a script. 
  hosts: all
  remote_user: jkolasinski
  ignore_errors: yes
  become: yes
  become_method: sudo

  tasks:
       - name: Copy and Execute the script
         script: /home/jkolasinski/scripts/audit.sh

       - fetch:
               src: /tmp/audit.log
               dest: /var/www/html/audyt/RH7
