---
- name: change user password 
  hosts: all
  ignore_errors: yes
  become: yes
  become_method: su
  become_user: root
  vars:
     # created with:
     # python -c 'import crypt; print crypt.crypt("password", "$1$SomeSalt$")'

  tasks:
  - name: change user password
    user: name={{login}} update_password=always password="{{ 'password2'|password_hash('sha512', 'mysalt') }}"
